"""Move permissions to staff_profile

Revision ID: 086c9e8420e9
Revises: e7f4c53ea21a
Create Date: 2026-04-09 13:30:01.637450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '086c9e8420e9'
down_revision: Union[str, Sequence[str], None] = 'e7f4c53ea21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('teacher_profiles', 'verification_status', new_column_name='document_status')
    op.add_column('teacher_profiles', sa.Column('esewa_id', sa.Text(), nullable=True))
    op.add_column('teacher_profiles', sa.Column('is_payment_verified', sa.Boolean(), server_default='false', nullable=False))
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.alter_column('teacher_profiles', 'document_status', new_column_name='verification_status')
    op.drop_column('teacher_profiles', 'is_payment_verified')
    op.drop_column('teacher_profiles', 'esewa_id')
    op.drop_table('staff_profiles')
    # ### end Alembic commands ###
