"""add_sessions_status_column

Revision ID: 1dc12671825a
Revises: fix_enums_001
Create Date: 2026-03-30 23:13:06.161109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dc12671825a'
down_revision: Union[str, Sequence[str], None] = 'fix_enums_001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_booking_student_status', 'bookings', ['student_id', 'status'], unique=False)
    op.create_index('ix_booking_teacher_status', 'bookings', ['teacher_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_booking_teacher_status', table_name='bookings')
    op.drop_index('ix_booking_student_status', table_name='bookings')
    # ### end Alembic commands ###
