"""Rename audit log metadata to action_metadata

Revision ID: 1eb3c77f90bf
Revises: 14b91d6fbe0a
Create Date: 2026-04-06 14:54:06.335991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb3c77f90bf'
down_revision: Union[str, Sequence[str], None] = '14b91d6fbe0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
