"""Add University, Faculty models

Revision ID: 39713078d256
Revises: dac9e758e8be
Create Date: 2026-04-02 12:03:54.453840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39713078d256'
down_revision: Union[str, Sequence[str], None] = 'dac9e758e8be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universities',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('faculties',
    sa.Column('university_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('number_of_semesters', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_name'), 'faculties', ['name'], unique=False)
    op.create_index(op.f('ix_faculties_university_id'), 'faculties', ['university_id'], unique=False)
    op.drop_index(op.f('ix_message_conversation'), table_name='messages')
    op.drop_index(op.f('ix_message_created'), table_name='messages')
    op.drop_index(op.f('ix_message_receiver_unread'), table_name='messages')
    op.drop_index(op.f('ix_message_sender_receiver'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.add_column('subjects', sa.Column('university_id', sa.UUID(), nullable=True))
    op.add_column('subjects', sa.Column('faculty_id', sa.UUID(), nullable=True))
    op.add_column('subjects', sa.Column('semester_number', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_subject_level_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_level'), table_name='subjects')
    op.drop_constraint(op.f('uq_subject_catalog'), 'subjects', type_='unique')
    op.create_index('ix_subject_faculty_semester', 'subjects', ['faculty_id', 'semester_number'], unique=False)
    op.create_index(op.f('ix_subjects_faculty_id'), 'subjects', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_subjects_university_id'), 'subjects', ['university_id'], unique=False)
    op.create_unique_constraint('uq_subject_per_faculty_semester', 'subjects', ['name', 'faculty_id', 'semester_number'])
    op.create_foreign_key(None, 'subjects', 'universities', ['university_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'subjects', 'faculties', ['faculty_id'], ['id'], ondelete='CASCADE')
    op.drop_column('subjects', 'faculty')
    op.drop_column('subjects', 'university')
    op.drop_column('subjects', 'level')
    op.drop_column('subjects', 'board')
    op.drop_column('subjects', 'semester')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('semester', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('board', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('level', postgresql.ENUM('CLASS_8', 'CLASS_9', 'CLASS_10', 'CLASS_11', 'CLASS_12', 'DIPLOMA', 'BACHELOR', 'MASTER', 'PHD', name='studylevel'), autoincrement=False, nullable=False))
    op.add_column('subjects', sa.Column('university', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('subjects', sa.Column('faculty', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_constraint('uq_subject_per_faculty_semester', 'subjects', type_='unique')
    op.drop_index(op.f('ix_subjects_university_id'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_faculty_id'), table_name='subjects')
    op.drop_index('ix_subject_faculty_semester', table_name='subjects')
    op.create_unique_constraint(op.f('uq_subject_catalog'), 'subjects', ['name', 'level', 'board', 'university', 'faculty', 'semester'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_subjects_level'), 'subjects', ['level'], unique=False)
    op.create_index(op.f('ix_subject_level_name'), 'subjects', ['level', 'name'], unique=False)
    op.drop_column('subjects', 'semester_number')
    op.drop_column('subjects', 'faculty_id')
    op.drop_column('subjects', 'university_id')
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('notification_type', postgresql.ENUM('BOOKING_REQUESTED', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'PAYMENT_RECEIVED', 'SESSION_INITIATED', 'SESSION_ACCEPTED', 'SESSION_STARTED', 'SESSION_COMPLETED', 'SESSION_CANCELLED', 'MESSAGE_RECEIVED', 'SYSTEM', name='notificationtype'), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('payload', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('notifications_booking_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('notifications_sender_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('notifications_session_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('notifications_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'FILE', 'SESSION_REQUEST', name='messagetype'), server_default=sa.text("'TEXT'::messagetype"), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_OFFLINE', 'ONGOING', 'ACCEPTED', 'REJECTED', 'MISSED', name='messagestatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('messages_booking_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('messages_receiver_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_message_sender_receiver'), 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index(op.f('ix_message_receiver_unread'), 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_message_created'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation'), 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_faculties_university_id'), table_name='faculties')
    op.drop_index(op.f('ix_faculties_name'), table_name='faculties')
    op.drop_table('faculties')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_table('universities')
    # ### end Alembic commands ###
