"""Add permissions and mfa_enabled to User model

Revision ID: 3f908c5fa566
Revises: b82c990d3a88
Create Date: 2026-04-06 14:18:55.692059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f908c5fa566'
down_revision: Union[str, Sequence[str], None] = 'b82c990d3a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('permissions', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False))
    op.add_column('users', sa.Column('mfa_enabled', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'mfa_enabled')
    op.drop_column('users', 'permissions')
    # ### end Alembic commands ###
