"""Complete schema consolidation with booking-based ratings and all features

Revision ID: 407f4ff27b91
Revises: 4b6ea5e158b8
Create Date: 2026-03-27 17:25:50.229559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '407f4ff27b91'
down_revision: Union[str, Sequence[str], None] = '4b6ea5e158b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
