"""Remove teacher_approval_notes field from booking

Revision ID: 49ac872f04b1
Revises: create_messages_explicit
Create Date: 2026-04-04 21:04:01.403048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '49ac872f04b1'
down_revision: Union[str, Sequence[str], None] = 'create_messages_explicit'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_conversation'), table_name='messages')
    op.drop_index(op.f('ix_message_created'), table_name='messages')
    op.drop_index(op.f('ix_message_receiver_unread'), table_name='messages')
    op.drop_index(op.f('ix_message_sender_receiver'), table_name='messages')
    op.drop_table('messages')
    op.drop_column('bookings', 'teacher_approval_notes')
    op.alter_column('subjects', 'university_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'faculty_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('subjects', 'semester_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('subjects', 'semester_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('subjects', 'faculty_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('subjects', 'university_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('bookings', sa.Column('teacher_approval_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'FILE', 'SESSION_REQUEST', name='messagetype'), server_default=sa.text("'TEXT'::messagetype"), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_key', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_OFFLINE', 'ONGOING', 'ACCEPTED', 'REJECTED', 'MISSED', name='messagestatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('messages_booking_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('messages_receiver_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_message_sender_receiver'), 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index(op.f('ix_message_receiver_unread'), 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_message_created'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation'), 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
