"""initial schema

Revision ID: 4b6ea5e158b8
Revises: 
Create Date: 2026-03-16 11:50:30.143781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6ea5e158b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('level', sa.Enum('CLASS_8', 'CLASS_9', 'CLASS_10', 'CLASS_11', 'CLASS_12', 'DIPLOMA', 'BACHELOR', 'MASTER', 'PHD', name='studylevel'), nullable=False),
    sa.Column('board', sa.String(length=100), nullable=True),
    sa.Column('university', sa.String(length=200), nullable=True),
    sa.Column('faculty', sa.String(length=200), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('class_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'level', 'board', 'university', 'faculty', 'semester', name='uq_subject_catalog')
    )
    op.create_index('ix_subject_level_name', 'subjects', ['level', 'name'], unique=False)
    op.create_index(op.f('ix_subjects_level'), 'subjects', ['level'], unique=False)
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('payment_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('esewa_phone', sa.String(length=20), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verification_screenshot_url', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_accounts_user_id'), 'payment_accounts', ['user_id'], unique=True)
    op.create_table('student_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('bookings',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('completed_sessions', sa.Integer(), nullable=False),
    sa.Column('cancelled_sessions', sa.Integer(), nullable=False),
    sa.Column('session_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('rate_per_session', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('escrow_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'PENDING_PAYMENT', 'ACTIVE', 'COMPLETED', 'CANCELLED_BY_STUDENT', 'CANCELLED_BY_TEACHER', 'DISPUTED', name='bookingstatus'), nullable=False),
    sa.Column('teacher_approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_approval_notes', sa.Text(), nullable=True),
    sa.Column('esewa_transaction_uuid', sa.Text(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('completed_sessions + cancelled_sessions <= total_sessions', name='chk_session_counts'),
    sa.CheckConstraint('total_sessions > 0', name='chk_total_sessions_positive'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('esewa_transaction_uuid')
    )
    op.create_index('ix_booking_student_status', 'bookings', ['student_id', 'status'], unique=False)
    op.create_index('ix_booking_teacher_status', 'bookings', ['teacher_id', 'status'], unique=False)
    op.create_index(op.f('ix_bookings_status'), 'bookings', ['status'], unique=False)
    op.create_index(op.f('ix_bookings_student_id'), 'bookings', ['student_id'], unique=False)
    op.create_index(op.f('ix_bookings_teacher_id'), 'bookings', ['teacher_id'], unique=False)
    op.create_table('payouts',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('gross_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('platform_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='payoutstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('esewa_ref_id', sa.Text(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('net_amount > 0', name='chk_payout_net_positive'),
    sa.CheckConstraint('period_end > period_start', name='chk_payout_period'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('teacher_id', 'period_start', 'period_end', name='uq_payout_teacher_period')
    )
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_index(op.f('ix_payouts_teacher_id'), 'payouts', ['teacher_id'], unique=False)
    op.create_table('teacher_documents',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('SELFIE', 'CITIZENSHIP_FRONT', 'CITIZENSHIP_BACK', 'PAN_CARD', 'SELFIE_WITH_CITIZENSHIP', name='documenttype'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='verificationstatus'), nullable=False),
    sa.Column('verified_by_id', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_documents_teacher_id'), 'teacher_documents', ['teacher_id'], unique=False)
    op.create_table('teacher_subjects',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('rate_per_session', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('total_sessions_completed', sa.Integer(), nullable=False),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('avg_rating >= 0 AND avg_rating <= 5', name='chk_avg_rating_range'),
    sa.CheckConstraint('rate_per_session > 0', name='chk_rate_positive'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'subject_id')
    )
    op.create_index('ix_teacher_subject_search', 'teacher_subjects', ['subject_id', 'avg_rating', 'total_sessions_completed'], unique=False)
    op.create_table('sessions',
    sa.Column('booking_id', sa.UUID(), nullable=False),
    sa.Column('session_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_STUDENT_ACCEPTANCE', 'SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED_BY_STUDENT', 'CANCELLED_BY_TEACHER', name='sessionstatus'), nullable=False),
    sa.Column('teacher_initiated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('livekit_room_name', sa.Text(), nullable=True),
    sa.Column('recording_url', sa.Text(), nullable=True),
    sa.Column('recording_key', sa.Text(), nullable=True),
    sa.Column('actual_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('teacher_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('student_joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('duration_minutes > 0', name='chk_duration_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livekit_room_name')
    )
    op.create_index('ix_session_booking_number', 'sessions', ['booking_id', 'session_number'], unique=False)
    op.create_index(op.f('ix_sessions_booking_id'), 'sessions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_sessions_status'), 'sessions', ['status'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('type', sa.Enum('DEBIT', 'CREDIT', name='transactiontype'), nullable=False),
    sa.Column('reason', sa.Enum('BOOKING_ESCROW', 'SESSION_RELEASE', 'REFUND_CANCELLED', 'WEEKLY_PAYOUT', 'PLATFORM_FEE', name='transactionreason'), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('payout_id', sa.UUID(), nullable=True),
    sa.Column('esewa_ref_id', sa.Text(), nullable=True),
    sa.Column('esewa_transaction_uuid', sa.Text(), nullable=True),
    sa.Column('esewa_status', sa.Enum('SUCCESS', 'FAILURE', 'PENDING', name='esewacallbackstatus'), nullable=True),
    sa.Column('metadata', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='chk_transaction_amount_positive'),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transaction_user_reason', 'transactions', ['user_id', 'reason'], unique=False)
    op.create_index(op.f('ix_transactions_booking_id'), 'transactions', ['booking_id'], unique=False)
    op.create_index(op.f('ix_transactions_esewa_ref_id'), 'transactions', ['esewa_ref_id'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('reporter_id', sa.UUID(), nullable=False),
    sa.Column('reported_user_id', sa.UUID(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('evidence_session_id', sa.UUID(), nullable=True),
    sa.Column('reason', sa.Enum('INAPPROPRIATE_CONTENT', 'HARASSMENT', 'NO_SHOW', 'FRAUD', 'POOR_QUALITY', 'OTHER', name='reportreason'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence_recording_url', sa.Text(), nullable=True),
    sa.Column('evidence_urls', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'RESOLVED', 'DISMISSED', name='reportstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['evidence_session_id'], ['sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reported_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_report_status_created', 'reports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_reports_booking_id'), 'reports', ['booking_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('teacher_ratings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='chk_rating_score_range'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_teacher_ratings_teacher_id'), 'teacher_ratings', ['teacher_id'], unique=False)
    op.create_table('user_bans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('report_id', sa.UUID(), nullable=True),
    sa.Column('banned_by_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_recording_url', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'LIFTED', name='banstatus'), nullable=False),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifted_by_id', sa.UUID(), nullable=True),
    sa.Column('lift_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['banned_by_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['lifted_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_bans_status'), 'user_bans', ['status'], unique=False)
    op.create_index(op.f('ix_user_bans_user_id'), 'user_bans', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_bans_user_id'), table_name='user_bans')
    op.drop_index(op.f('ix_user_bans_status'), table_name='user_bans')
    op.drop_table('user_bans')
    op.drop_index(op.f('ix_teacher_ratings_teacher_id'), table_name='teacher_ratings')
    op.drop_table('teacher_ratings')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_booking_id'), table_name='reports')
    op.drop_index('ix_report_status_created', table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_esewa_ref_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_booking_id'), table_name='transactions')
    op.drop_index('ix_transaction_user_reason', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_sessions_status'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_booking_id'), table_name='sessions')
    op.drop_index('ix_session_booking_number', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_teacher_subject_search', table_name='teacher_subjects')
    op.drop_table('teacher_subjects')
    op.drop_index(op.f('ix_teacher_documents_teacher_id'), table_name='teacher_documents')
    op.drop_table('teacher_documents')
    op.drop_index(op.f('ix_payouts_teacher_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_bookings_teacher_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_student_id'), table_name='bookings')
    op.drop_index(op.f('ix_bookings_status'), table_name='bookings')
    op.drop_index('ix_booking_teacher_status', table_name='bookings')
    op.drop_index('ix_booking_student_status', table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('teacher_profiles')
    op.drop_table('student_profiles')
    op.drop_index(op.f('ix_payment_accounts_user_id'), table_name='payment_accounts')
    op.drop_table('payment_accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.drop_index(op.f('ix_subjects_level'), table_name='subjects')
    op.drop_index('ix_subject_level_name', table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
