"""academics_update

Revision ID: 5d323c092d6f
Revises: 61d3ea5d79ed
Create Date: 2026-04-06 15:02:33.460766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d323c092d6f'
down_revision: Union[str, Sequence[str], None] = '61d3ea5d79ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_levels_study_level_id'), table_name='class_levels')
    op.drop_table('class_levels')
    op.add_column('board_study_levels', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('boards', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('faculties', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('study_levels', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('subjects', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjects', 'is_active')
    op.drop_column('study_levels', 'is_active')
    op.drop_column('faculties', 'is_active')
    op.drop_column('boards', 'is_active')
    op.drop_column('board_study_levels', 'is_active')
    op.create_table('class_levels',
    sa.Column('study_level_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('level_order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['study_level_id'], ['study_levels.id'], name=op.f('class_levels_study_level_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('class_levels_pkey'))
    )
    op.create_index(op.f('ix_class_levels_study_level_id'), 'class_levels', ['study_level_id'], unique=False)
    # ### end Alembic commands ###
