"""add_communication_models

Revision ID: 83c2a4fedb33
Revises: c2918cbb42af
Create Date: 2026-04-17 09:29:50.465171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '83c2a4fedb33'
down_revision: Union[str, Sequence[str], None] = 'c2918cbb42af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', postgresql.ENUM('TEXT', 'FILE', 'SESSION_REQUEST', name='messagetype', create_type=False), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_key', sa.String(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING_OFFLINE', 'ONGOING', 'ACCEPTED', 'REJECTED', 'MISSED', name='messagestatus', create_type=False), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_conversation', 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.create_index('ix_message_created', 'messages', ['created_at'], unique=False)
    op.create_index('ix_message_receiver_unread', 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index('ix_message_sender_receiver', 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', postgresql.ENUM('BOOKING_REQUESTED', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'PAYMENT_RECEIVED', 'SESSION_INITIATED', 'SESSION_ACCEPTED', 'SESSION_STARTED', 'SESSION_COMPLETED', 'SESSION_CANCELLED', 'MESSAGE_RECEIVED', 'SYSTEM', name='notificationtype', create_type=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_booking', 'notifications', ['booking_id'], unique=False)
    op.create_index('ix_notification_session', 'notifications', ['session_id'], unique=False)
    op.create_index('ix_notification_type', 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notification_unread', 'notifications', ['user_id', 'is_read'], unique=False)
    op.create_index('ix_notification_user_created', 'notifications', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index('ix_notification_user_created', table_name='notifications')
    op.drop_index('ix_notification_unread', table_name='notifications')
    op.drop_index('ix_notification_type', table_name='notifications')
    op.drop_index('ix_notification_session', table_name='notifications')
    op.drop_index('ix_notification_booking', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index('ix_message_sender_receiver', table_name='messages')
    op.drop_index('ix_message_receiver_unread', table_name='messages')
    op.drop_index('ix_message_created', table_name='messages')
    op.drop_index('ix_message_conversation', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
