"""sync_academics_models

Revision ID: b82c990d3a88
Revises: remove_is_active_from_subject
Create Date: 2026-04-06 14:09:55.961703

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b82c990d3a88'
down_revision: Union[str, Sequence[str], None] = 'remove_is_active_from_subject'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_levels',
    sa.Column('study_level_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('level_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['study_level_id'], ['study_levels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_levels_study_level_id'), 'class_levels', ['study_level_id'], unique=False)
    op.drop_index(op.f('ix_board_study_levels_board'), table_name='board_study_levels')
    op.drop_index(op.f('ix_board_study_levels_study_level'), table_name='board_study_levels')
    op.create_foreign_key(None, 'bookings', 'subjects', ['subject_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('faculties', 'unit_type',
               existing_type=postgresql.ENUM('GRADE', 'SEMESTER', 'YEAR', name='unittype'),
               comment='GRADE, SEMESTER, or YEAR',
               existing_nullable=False)
    op.alter_column('faculties', 'total_units',
               existing_type=sa.INTEGER(),
               comment='Total count (e.g., 8 for 8 semesters in BSc. CSIT)',
               existing_nullable=False)
    op.drop_constraint(op.f('uq_study_levels_name'), 'study_levels', type_='unique')
    op.alter_column('subjects', 'unit_value',
               existing_type=sa.INTEGER(),
               comment="Numeric grade/semester/year (1-N, validated against faculty's total_units)",
               existing_nullable=False)
    op.create_foreign_key(None, 'teacher_ratings', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'teacher_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'teacher_subjects', type_='foreignkey')
    op.drop_constraint(None, 'teacher_ratings', type_='foreignkey')
    op.alter_column('subjects', 'unit_value',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment="Numeric grade/semester/year (1-N, validated against faculty's total_units)",
               existing_nullable=False)
    op.create_unique_constraint(op.f('uq_study_levels_name'), 'study_levels', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('faculties', 'total_units',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Total count (e.g., 8 for 8 semesters in BSc. CSIT)',
               existing_nullable=False)
    op.alter_column('faculties', 'unit_type',
               existing_type=postgresql.ENUM('GRADE', 'SEMESTER', 'YEAR', name='unittype'),
               comment=None,
               existing_comment='GRADE, SEMESTER, or YEAR',
               existing_nullable=False)
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_index(op.f('ix_board_study_levels_study_level'), 'board_study_levels', ['study_level_id'], unique=False)
    op.create_index(op.f('ix_board_study_levels_board'), 'board_study_levels', ['board_id'], unique=False)
    op.drop_index(op.f('ix_class_levels_study_level_id'), table_name='class_levels')
    op.drop_table('class_levels')
    # ### end Alembic commands ###
