"""empty message

Revision ID: c2918cbb42af
Revises: 8b3d2f1a9c3b
Create Date: 2026-04-16 20:49:12.502357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c2918cbb42af'
down_revision: Union[str, Sequence[str], None] = '8b3d2f1a9c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_conversation'), table_name='messages')
    op.drop_index(op.f('ix_message_created'), table_name='messages')
    op.drop_index(op.f('ix_message_receiver_unread'), table_name='messages')
    op.drop_index(op.f('ix_message_sender_receiver'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_session_booking_number'), table_name='sessions')
    op.create_unique_constraint('uq_booking_session_number', 'sessions', ['booking_id', 'session_number'])
    op.drop_index(op.f('idx_subjects_name_trgm'), table_name='subjects', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_subjects_name_trgm'), table_name='subjects', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_subjects_name'), 'subjects', ['name'], unique=False)
    op.drop_index(op.f('ix_transaction_session_id'), table_name='transactions')
    op.create_index(op.f('ix_transactions_session_id'), 'transactions', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_session_id'), table_name='transactions')
    op.create_index(op.f('ix_transaction_session_id'), 'transactions', ['session_id'], unique=False)
    op.drop_index(op.f('ix_subjects_name'), table_name='subjects')
    op.create_index(op.f('ix_subjects_name_trgm'), 'subjects', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_subjects_name_trgm'), 'subjects', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint('uq_booking_session_number', 'sessions', type_='unique')
    op.create_index(op.f('ix_session_booking_number'), 'sessions', ['booking_id', 'session_number'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('receiver_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('message_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('file_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_public_id', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('booking_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('file_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], name=op.f('messages_booking_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], name=op.f('messages_receiver_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('messages_session_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_message_sender_receiver'), 'messages', ['sender_id', 'receiver_id'], unique=False)
    op.create_index(op.f('ix_message_receiver_unread'), 'messages', ['receiver_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_message_created'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_message_conversation'), 'messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
