"""Add study_level_id to Faculty

Revision ID: e7f4c53ea21a
Revises: 5d323c092d6f
Create Date: 2026-04-06 15:08:15.828004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f4c53ea21a'
down_revision: Union[str, Sequence[str], None] = '5d323c092d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculties', sa.Column('study_level_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_faculties_study_level_id'), 'faculties', ['study_level_id'], unique=False)
    op.create_foreign_key(None, 'faculties', 'study_levels', ['study_level_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'faculties', type_='foreignkey')
    op.drop_index(op.f('ix_faculties_study_level_id'), table_name='faculties')
    op.drop_column('faculties', 'study_level_id')
    # ### end Alembic commands ###
